const CREATE_POST = 'CREATE_POST'
const GET_DATA_DONE = 'GET_DATA_DONE'
const DELETE_POST = 'DELETE_POST'
const DELETE_POST_ERROR = 'DELETE_POST_ERROR'

export { CREATE_POST, DELETE_POST, GET_DATA_DONE, DELETE_POST_ERROR }
